name: Publish

on:
  push:
    branches: [ "master", "fix_publish" ]

env:
  PUB_FEED: ${{ secrets.PUB_FEED }}
  PUB_FEED_ACCESS_TOKEN: ${{ secrets.PUB_FEED_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: echo $PUB_FEED_ACCESS_TOKEN | dart pub token add $PUB_FEED
      - run: dart pub publish --dry-run --server $PUB_FEED
